### ISSUE TITLE
Make CTest Optional

### ISSUE THREAD

**Issue by K3rn1n4tor** [guybrush77/rapidobj#15]
We use rapidobj in a project and noticed that it includes CTest. However, since we perform our unit tests with catch2, CTest is not needed.

I would suggest that we simply add a global define that allows projects using Rapidobj to skip `include(CTest)` or any other test-related projects.

**Comment by guybrush77** [comment]
There already exists `RAPIDOBJ_BuildTests`. So now I only include CTest when `RAPIDOBJ_BuildTests` is defined. Please take a look at the latest master. Does this fix your issue?

**Comment by K3rn1n4tor** [comment]
That should fix it, I'll test this by the end of the week. :) Thanks.

**Comment by guybrush77** [comment]
Should be fixed in the new release (v1.1).
